export const entertainmentVenues = [
  {
    id: 'ev1',
    name: 'Six Flags Qiddiya',
    nameAr: 'سيكس فلاقز القدية',
    description: 'The first Six Flags theme park in Saudi Arabia, located in Qiddiya Entertainment City. Features world-record-breaking roller coasters, family rides, and immersive themed zones.',
    type: 'theme_park' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg/800px-Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Riyadh_city_%282014%29.jpg/800px-Riyadh_city_%282014%29.jpg'],
    city: 'Riyadh',
    latitude: 24.4539,
    longitude: 46.5722,
    ticketTypes: [
      { id: 'tt1', name: 'Standard Day Pass', price: 249, currency: 'SAR', description: 'Full day access to all standard rides', available: 500 },
      { id: 'tt2', name: 'Premium Day Pass', price: 399, currency: 'SAR', description: 'Priority access + premium rides', available: 200 },
      { id: 'tt3', name: 'VIP Experience', price: 599, currency: 'SAR', description: 'Skip-the-line + VIP lounge + complimentary meal', available: 50 },
      { id: 'tt4', name: 'Family Pack (4)', price: 849, currency: 'SAR', description: '4 standard passes at discounted rate', available: 150 },
    ],
    rating: 4.7,
    openingHours: '10:00 AM - 11:00 PM',
    features: ['Roller Coasters', 'Water Rides', 'Family Zone', 'VIP Lounge', 'Food Court', 'Gift Shop', 'Parking'],
  },
  {
    id: 'ev2',
    name: 'Boulevard Riyadh City',
    nameAr: 'بوليفارد رياض سيتي',
    description: 'The heart of Riyadh Season entertainment district featuring world-class restaurants, live shows, themed zones, and interactive experiences spanning over 900,000 sqm.',
    type: 'entertainment_complex' as const,
    images: ['https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Kingdom_Centre_Riyadh_2024.jpeg/800px-Kingdom_Centre_Riyadh_2024.jpeg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/KAFD_seen_from_North_east_side_of_Riyadh_City.jpg/800px-KAFD_seen_from_North_east_side_of_Riyadh_City.jpg'],
    city: 'Riyadh',
    latitude: 24.7528,
    longitude: 46.6457,
    ticketTypes: [
      { id: 'tt5', name: 'General Entry', price: 30, currency: 'SAR', description: 'Access to Boulevard zones and walkways', available: 5000 },
      { id: 'tt6', name: 'Premium Entry', price: 75, currency: 'SAR', description: 'Priority entry + select show access', available: 1000 },
    ],
    rating: 4.5,
    openingHours: '4:00 PM - 2:00 AM',
    features: ['Live Shows', 'Restaurants', 'Shopping', 'Themed Zones', 'Fireworks', 'Celebrity Appearances'],
  },
  {
    id: 'ev3',
    name: 'Boulevard World',
    nameAr: 'بوليفارد وورلد',
    description: 'A global cultural destination within Riyadh Season featuring pavilions representing countries from around the world with authentic cuisine, performances, and shopping.',
    type: 'entertainment_complex' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/At-Turaif_District_of_Diriyah%2C_Saudi_Arabia.jpg/800px-At-Turaif_District_of_Diriyah%2C_Saudi_Arabia.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/National_Museum_Riyadh_%286781666263%29.jpg/800px-National_Museum_Riyadh_%286781666263%29.jpg'],
    city: 'Riyadh',
    latitude: 24.7600,
    longitude: 46.6500,
    ticketTypes: [
      { id: 'tt7', name: 'General Entry', price: 35, currency: 'SAR', description: 'Full access to all world pavilions', available: 3000 },
      { id: 'tt8', name: 'VIP Experience', price: 150, currency: 'SAR', description: 'VIP lounge + exclusive dining + priority', available: 200 },
    ],
    rating: 4.4,
    openingHours: '4:00 PM - 1:00 AM',
    features: ['World Pavilions', 'Cultural Shows', 'International Cuisine', 'Shopping', 'Carnival Games'],
  },
  {
    id: 'ev4',
    name: 'Winter Wonderland Riyadh',
    nameAr: 'وينتر وندرلاند الرياض',
    description: 'A magical winter-themed entertainment park in the heart of Riyadh featuring ice skating, snow activities, carnival rides, and festive performances.',
    type: 'theme_park' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Riyadh_city_%282014%29.jpg/800px-Riyadh_city_%282014%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/KAFD_January_2025.jpg/800px-KAFD_January_2025.jpg'],
    city: 'Riyadh',
    latitude: 24.7400,
    longitude: 46.6300,
    ticketTypes: [
      { id: 'tt9', name: 'Day Pass', price: 99, currency: 'SAR', description: 'Full day access to all attractions', available: 2000 },
      { id: 'tt10', name: 'Family Bundle (4)', price: 349, currency: 'SAR', description: '4 day passes + meal vouchers', available: 500 },
    ],
    rating: 4.3,
    openingHours: '3:00 PM - 12:00 AM',
    features: ['Ice Skating', 'Snow Park', 'Carnival Rides', 'Live Shows', 'Food Stalls'],
  },
  {
    id: 'ev5',
    name: 'Via Riyadh',
    nameAr: 'فيا الرياض',
    description: 'An upscale lifestyle destination in Riyadh combining luxury shopping, fine dining, and entertainment in a stunning architectural setting inspired by European piazzas.',
    type: 'entertainment_complex' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/BSM_2571.jpg/800px-BSM_2571.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg/800px-Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg'],
    city: 'Riyadh',
    latitude: 24.7200,
    longitude: 46.6700,
    ticketTypes: [
      { id: 'tt11', name: 'Free Entry', price: 0, currency: 'SAR', description: 'Open access to public areas', available: 10000 },
    ],
    rating: 4.6,
    openingHours: '10:00 AM - 12:00 AM',
    features: ['Luxury Dining', 'Designer Shopping', 'Art Galleries', 'Water Features', 'Events Space'],
  },
  {
    id: 'ev6',
    name: 'Maraya Concert Hall',
    nameAr: 'قاعة مرايا',
    description: 'The world\'s largest mirrored building nestled in the AlUla desert. This stunning concert hall hosts international artists and cultural events against a backdrop of ancient Nabataean landscapes.',
    type: 'concert_venue' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Hegra%2C_Al-Ula%2C_Saudi_Arabia.png/800px-Hegra%2C_Al-Ula%2C_Saudi_Arabia.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Elephant_rock%2C_Al-%27Ula.jpg/800px-Elephant_rock%2C_Al-%27Ula.jpg'],
    city: 'AlUla',
    latitude: 26.6174,
    longitude: 37.9187,
    ticketTypes: [
      { id: 'tt12', name: 'Concert Ticket', price: 350, currency: 'SAR', description: 'Standard seating', available: 500 },
      { id: 'tt13', name: 'VIP Front Row', price: 1200, currency: 'SAR', description: 'Front rows + backstage access', available: 50 },
    ],
    rating: 4.9,
    openingHours: 'Event-based',
    features: ['World-class Acoustics', 'Mirrored Architecture', 'Desert Setting', 'VIP Lounge', 'Fine Dining'],
  },
  {
    id: 'ev7',
    name: 'Boulevard Jeddah',
    nameAr: 'بوليفارد جدة',
    description: 'Jeddah\'s premier entertainment destination along the waterfront, featuring seaside dining, live performances, amusement rides, and the vibrant energy of Jeddah Season.',
    type: 'entertainment_complex' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Jeddah_Corniche.jpg/800px-Jeddah_Corniche.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jeddah_Tower_in_its_88th_floor_%28cropped%29.jpg/800px-Jeddah_Tower_in_its_88th_floor_%28cropped%29.jpg'],
    city: 'Jeddah',
    latitude: 21.5433,
    longitude: 39.1728,
    ticketTypes: [
      { id: 'tt14', name: 'General Entry', price: 25, currency: 'SAR', description: 'Full access to boulevard areas', available: 4000 },
    ],
    rating: 4.4,
    openingHours: '5:00 PM - 2:00 AM',
    features: ['Waterfront Dining', 'Live Music', 'Amusement Rides', 'Fireworks', 'Artisan Markets'],
  },
  {
    id: 'ev8',
    name: 'Jeddah Waterfront (Corniche)',
    nameAr: 'واجهة جدة البحرية',
    description: 'The iconic Jeddah Corniche stretching 30km along the Red Sea coast, offering boat tours, water sports, sculpture gardens, and stunning views of King Fahad Fountain.',
    type: 'waterfront' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/King_Fahd%E2%80%99s_Fountain.jpg/800px-King_Fahd%E2%80%99s_Fountain.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Old_Jeddah_%28Al_Balad%29_architecture_3_Feb_2022.jpg/800px-Old_Jeddah_%28Al_Balad%29_architecture_3_Feb_2022.jpg'],
    city: 'Jeddah',
    latitude: 21.5726,
    longitude: 39.1065,
    ticketTypes: [
      { id: 'tt15', name: 'Free Access', price: 0, currency: 'SAR', description: 'Public waterfront access', available: 10000 },
      { id: 'tt16', name: 'Boat Tour', price: 150, currency: 'SAR', description: '1-hour Red Sea boat tour', available: 100 },
    ],
    rating: 4.3,
    openingHours: 'Open 24 hours',
    features: ['Boat Tours', 'Water Sports', 'Sculpture Garden', 'Cycling Path', 'Cafes', 'Playground'],
  },
  {
    id: 'ev9',
    name: 'The Groves',
    nameAr: 'ذا جروفز',
    description: 'A family-friendly entertainment complex in Riyadh featuring indoor theme parks, play zones, dining, and immersive experiences for all ages.',
    type: 'theme_park' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/National_Museum_Riyadh_%286781666263%29.jpg/800px-National_Museum_Riyadh_%286781666263%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Masmak_Fort_%2812753717253%29.jpg/800px-Masmak_Fort_%2812753717253%29.jpg'],
    city: 'Riyadh',
    latitude: 24.7100,
    longitude: 46.6800,
    ticketTypes: [
      { id: 'tt17', name: 'Kids Pass', price: 89, currency: 'SAR', description: 'Full day access for children under 12', available: 1000 },
      { id: 'tt18', name: 'Family Pass (2+2)', price: 269, currency: 'SAR', description: '2 adults + 2 children', available: 300 },
    ],
    rating: 4.2,
    openingHours: '10:00 AM - 10:00 PM',
    features: ['Indoor Theme Park', 'Play Zones', 'Arcade', 'Food Court', 'Party Rooms'],
  },
  {
    id: 'ev10',
    name: 'Qiddiya Entertainment City',
    nameAr: 'مدينة القدية الترفيهية',
    description: 'Saudi Arabia\'s mega entertainment destination spanning 334 sq km, featuring world-class theme parks, sports venues, nature experiences, and cultural attractions.',
    type: 'entertainment_complex' as const,
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/KAFD_seen_from_North_east_side_of_Riyadh_City.jpg/800px-KAFD_seen_from_North_east_side_of_Riyadh_City.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Tuwaiq_Escarpment%2C_Riyadh_%28cropped%29.jpg/800px-Tuwaiq_Escarpment%2C_Riyadh_%28cropped%29.jpg'],
    city: 'Riyadh',
    latitude: 24.4500,
    longitude: 46.5800,
    ticketTypes: [
      { id: 'tt19', name: 'Explorer Pass', price: 199, currency: 'SAR', description: 'Full day access to open zones', available: 2000 },
      { id: 'tt20', name: 'Ultimate Pass', price: 499, currency: 'SAR', description: 'All-access including premium experiences', available: 500 },
    ],
    rating: 4.8,
    openingHours: '9:00 AM - 11:00 PM',
    features: ['Theme Parks', 'Sports Arena', 'Water Park', 'Nature Trails', 'Motorsport', 'Golf Course'],
  },
];

export const entertainmentEvents = [
  {
    id: 'ee1',
    name: 'MDL Beast Soundstorm 2026',
    nameAr: 'ساوند ستورم 2026',
    description: 'The Middle East\'s largest music festival returns with over 200 artists across 8 stages. Three days of electronic, hip-hop, and pop music in the Riyadh desert.',
    type: 'concert' as const,
    venue: 'Banban, Riyadh',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Riyadh_city_%282014%29.jpg/800px-Riyadh_city_%282014%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/KAFD_seen_from_North_east_side_of_Riyadh_City.jpg/800px-KAFD_seen_from_North_east_side_of_Riyadh_City.jpg'],
    date: '2026-12-18',
    endDate: '2026-12-20',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et1', name: 'General Admission (1 Day)', price: 450, currency: 'SAR', description: 'Single day access to all stages', available: 10000 },
      { id: 'et2', name: '3-Day Pass', price: 999, currency: 'SAR', description: 'Full festival access all 3 days', available: 5000 },
      { id: 'et3', name: 'VIP (1 Day)', price: 1500, currency: 'SAR', description: 'VIP area + premium bars + viewing deck', available: 1000 },
      { id: 'et4', name: 'VVIP 3-Day', price: 2500, currency: 'SAR', description: 'All-access VVIP with private cabana', available: 200 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee2',
    name: 'Formula 1 Saudi Arabian Grand Prix 2026',
    nameAr: 'جائزة السعودية الكبرى فورمولا 1',
    description: 'The fastest street circuit in Formula 1 history. Watch the world\'s best drivers battle under the lights of the Jeddah Corniche Circuit.',
    type: 'sports' as const,
    venue: 'Jeddah Corniche Circuit',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Jeddah_Corniche.jpg/800px-Jeddah_Corniche.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/King_Fahd%E2%80%99s_Fountain.jpg/800px-King_Fahd%E2%80%99s_Fountain.jpg'],
    date: '2026-04-17',
    endDate: '2026-04-19',
    city: 'Jeddah',
    ticketTypes: [
      { id: 'et5', name: 'Grandstand (Sunday)', price: 750, currency: 'SAR', description: 'Race day grandstand seating', available: 3000 },
      { id: 'et6', name: '3-Day Grandstand', price: 1500, currency: 'SAR', description: 'All sessions Fri-Sun', available: 2000 },
      { id: 'et7', name: 'Paddock Club', price: 5000, currency: 'SAR', description: 'Premium hospitality + pit lane walk', available: 200 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee3',
    name: 'Saudi Cup 2026',
    nameAr: 'كأس السعودية 2026',
    description: 'The world\'s richest horse race with a $20 million purse. A spectacular day of thoroughbred racing, fashion, and entertainment at King Abdulaziz Racecourse.',
    type: 'sports' as const,
    venue: 'King Abdulaziz Racecourse',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg/800px-Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/KAFD_January_2025.jpg/800px-KAFD_January_2025.jpg'],
    date: '2026-02-28',
    endDate: '2026-02-28',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et8', name: 'General Admission', price: 100, currency: 'SAR', description: 'Racecourse access', available: 5000 },
      { id: 'et9', name: 'Premium Enclosure', price: 500, currency: 'SAR', description: 'Premium viewing + dining', available: 1000 },
      { id: 'et10', name: 'Royal Suite', price: 3000, currency: 'SAR', description: 'Private suite with 5-star hospitality', available: 50 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee4',
    name: 'Riyadh Season 2026 Opening',
    nameAr: 'افتتاح موسم الرياض 2026',
    description: 'The grand opening ceremony of Riyadh Season featuring international artists, dazzling fireworks, drone shows, and surprise celebrity appearances.',
    type: 'festival' as const,
    venue: 'Boulevard Riyadh City',
    images: ['https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Kingdom_Centre_Riyadh_2024.jpeg/800px-Kingdom_Centre_Riyadh_2024.jpeg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Riyadh_city_%282014%29.jpg/800px-Riyadh_city_%282014%29.jpg'],
    date: '2026-10-15',
    endDate: '2026-10-15',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et11', name: 'General Entry', price: 50, currency: 'SAR', description: 'Opening ceremony access', available: 20000 },
      { id: 'et12', name: 'VIP', price: 500, currency: 'SAR', description: 'Front stage + VIP area', available: 2000 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee5',
    name: 'Jeddah Season 2026',
    nameAr: 'موسم جدة 2026',
    description: 'Jeddah\'s annual entertainment season transforming the city\'s waterfront into a vibrant hub of concerts, cultural events, dining, and family attractions.',
    type: 'festival' as const,
    venue: 'Jeddah Waterfront',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Old_Jeddah_%28Al_Balad%29_architecture_3_Feb_2022.jpg/800px-Old_Jeddah_%28Al_Balad%29_architecture_3_Feb_2022.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jeddah_Tower_in_its_88th_floor_%28cropped%29.jpg/800px-Jeddah_Tower_in_its_88th_floor_%28cropped%29.jpg'],
    date: '2026-06-01',
    endDate: '2026-08-31',
    city: 'Jeddah',
    ticketTypes: [
      { id: 'et13', name: 'Season Pass', price: 199, currency: 'SAR', description: 'Unlimited entry throughout the season', available: 10000 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee6',
    name: 'AlUla Moments: Under the Stars',
    nameAr: 'لحظات العلا: تحت النجوم',
    description: 'An enchanting evening of live music and cultural performances set against the ancient Nabataean tombs of Hegra, illuminated under the desert stars.',
    type: 'concert' as const,
    venue: 'Maraya Concert Hall, AlUla',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Qasr_al_Farid.JPG/800px-Qasr_al_Farid.JPG', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Madain_Saleh_%286720185645%29.jpg/800px-Madain_Saleh_%286720185645%29.jpg'],
    date: '2026-11-20',
    endDate: '2026-11-22',
    city: 'AlUla',
    ticketTypes: [
      { id: 'et14', name: 'Standard', price: 350, currency: 'SAR', description: 'Open-air seating', available: 800 },
      { id: 'et15', name: 'Premium Lounge', price: 900, currency: 'SAR', description: 'Lounge seating + welcome drink', available: 200 },
      { id: 'et16', name: 'Stargazer VIP', price: 1800, currency: 'SAR', description: 'Private majlis + full dinner + desert tour', available: 50 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee7',
    name: 'WWE Crown Jewel 2026',
    nameAr: 'كراون جول 2026',
    description: 'WWE returns to Saudi Arabia with its biggest superstars battling for championship glory in one of the most anticipated events of the wrestling calendar.',
    type: 'sports' as const,
    venue: 'Mohammed Abdo Arena, Riyadh',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/KAFD_January_2025.jpg/800px-KAFD_January_2025.jpg', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Kingdom_Centre_Riyadh_2024.jpeg/800px-Kingdom_Centre_Riyadh_2024.jpeg'],
    date: '2026-11-01',
    endDate: '2026-11-01',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et17', name: 'Upper Bowl', price: 200, currency: 'SAR', description: 'Upper level seating', available: 5000 },
      { id: 'et18', name: 'Lower Bowl', price: 500, currency: 'SAR', description: 'Lower level seating', available: 3000 },
      { id: 'et19', name: 'Ringside', price: 2000, currency: 'SAR', description: 'Ringside seats + meet & greet chance', available: 200 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee8',
    name: 'Abha Summer Festival 2026',
    nameAr: 'مهرجان صيف أبها 2026',
    description: 'Escape the summer heat in the cool mountains of Abha. Enjoy cultural performances, local craft markets, nature hikes, and traditional Asiri food festivals.',
    type: 'festival' as const,
    venue: 'Abha City Center',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Rijal_Almaa_During_the_Day_2020.jpg/800px-Rijal_Almaa_During_the_Day_2020.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Rijal_Almaa_at_Night_2019.jpg/800px-Rijal_Almaa_at_Night_2019.jpg'],
    date: '2026-07-01',
    endDate: '2026-08-15',
    city: 'Abha',
    ticketTypes: [
      { id: 'et20', name: 'Free Entry', price: 0, currency: 'SAR', description: 'Open festival access', available: 50000 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee9',
    name: 'Taif Rose Festival 2026',
    nameAr: 'مهرجان ورد الطائف 2026',
    description: 'Celebrate the famous Taif rose harvest with fragrant garden tours, rose oil workshops, poetry readings, and a spectacular flower parade through the city.',
    type: 'festival' as const,
    venue: 'Taif Rose Gardens',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rijal_Alma_village_from_the_inside%2C_2021.jpg/800px-Rijal_Alma_village_from_the_inside%2C_2021.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Rijal_Almaa_During_the_Day_2020.jpg/800px-Rijal_Almaa_During_the_Day_2020.jpg'],
    date: '2026-04-01',
    endDate: '2026-04-15',
    city: 'Taif',
    ticketTypes: [
      { id: 'et21', name: 'Garden Tour', price: 50, currency: 'SAR', description: 'Guided rose garden tour', available: 500 },
      { id: 'et22', name: 'Workshop Pass', price: 150, currency: 'SAR', description: 'Tour + rose oil making workshop', available: 100 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee10',
    name: 'Desert X AlUla 2026',
    nameAr: 'ديزرت إكس العلا 2026',
    description: 'A site-specific contemporary art exhibition set in the breathtaking desert landscape of AlUla, featuring large-scale installations by international artists.',
    type: 'exhibition' as const,
    venue: 'AlUla Desert Valley',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Elephant_rock%2C_Al-%27Ula.jpg/800px-Elephant_rock%2C_Al-%27Ula.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Hegra%2C_Al-Ula%2C_Saudi_Arabia.png/800px-Hegra%2C_Al-Ula%2C_Saudi_Arabia.png'],
    date: '2026-02-09',
    endDate: '2026-03-30',
    city: 'AlUla',
    ticketTypes: [
      { id: 'et23', name: 'Exhibition Entry', price: 75, currency: 'SAR', description: 'Full exhibition access with audio guide', available: 2000 },
      { id: 'et24', name: 'Curator Tour', price: 250, currency: 'SAR', description: 'Guided tour with art curator + refreshments', available: 30 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee11',
    name: 'SPL: Al Hilal vs Al Nassr',
    nameAr: 'الدوري السعودي: الهلال ضد النصر',
    description: 'The biggest derby in Saudi football! Watch the clash of titans as Al Hilal faces Al Nassr in the Saudi Pro League at King Fahd Stadium.',
    type: 'sports' as const,
    venue: 'King Fahd International Stadium',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg/800px-Riyadh_Skyline_showing_the_pointed_Al_Faisaliyah_Center_tower_and_the_Kingdom_Centre_skyscraper_with_its_sky_bridge_-_panoramio.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Masmak_Citadel%2C_Riyadh_%2814374730992%29.jpg/800px-Masmak_Citadel%2C_Riyadh_%2814374730992%29.jpg'],
    date: '2026-05-10',
    endDate: '2026-05-10',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et25', name: 'Category 3', price: 50, currency: 'SAR', description: 'Upper tier seating', available: 10000 },
      { id: 'et26', name: 'Category 1', price: 200, currency: 'SAR', description: 'Midfield lower tier', available: 3000 },
      { id: 'et27', name: 'VVIP Box', price: 1500, currency: 'SAR', description: 'Private box for 4 with catering', available: 20 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee12',
    name: 'International Comedy Night',
    nameAr: 'ليلة الكوميديا الدولية',
    description: 'A night of laughter featuring top international and regional comedians performing stand-up comedy at Boulevard Riyadh City.',
    type: 'theater' as const,
    venue: 'Boulevard Riyadh City Theater',
    images: ['https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Kingdom_Centre_Riyadh_2024.jpeg/800px-Kingdom_Centre_Riyadh_2024.jpeg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/National_Museum_Riyadh_%286781666263%29.jpg/800px-National_Museum_Riyadh_%286781666263%29.jpg'],
    date: '2026-09-15',
    endDate: '2026-09-15',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et28', name: 'Standard', price: 150, currency: 'SAR', description: 'Theater seating', available: 800 },
      { id: 'et29', name: 'Front Row', price: 350, currency: 'SAR', description: 'Front 3 rows + meet & greet', available: 60 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee13',
    name: 'Tantura Winter Festival',
    nameAr: 'مهرجان شتاء طنطورة',
    description: 'AlUla\'s prestigious winter arts and music festival combining world-class musical performances with heritage celebrations in the ancient oasis town.',
    type: 'festival' as const,
    venue: 'AlUla Old Town',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Madain_Saleh_%286720185645%29.jpg/800px-Madain_Saleh_%286720185645%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Qasr_al_Farid.JPG/800px-Qasr_al_Farid.JPG'],
    date: '2026-12-20',
    endDate: '2027-01-15',
    city: 'AlUla',
    ticketTypes: [
      { id: 'et30', name: 'Single Event', price: 300, currency: 'SAR', description: 'One performance of your choice', available: 1000 },
      { id: 'et31', name: 'Weekend Pass', price: 750, currency: 'SAR', description: 'All events across a weekend', available: 300 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
  {
    id: 'ee14',
    name: 'Riyadh International Film Festival',
    nameAr: 'مهرجان الرياض السينمائي الدولي',
    description: 'Showcasing the best of Arab and international cinema with premieres, director Q&As, workshops, and red carpet events across multiple venues.',
    type: 'exhibition' as const,
    venue: 'King Abdullah Financial District',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/KAFD_seen_from_North_east_side_of_Riyadh_City.jpg/800px-KAFD_seen_from_North_east_side_of_Riyadh_City.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/KAFD_January_2025.jpg/800px-KAFD_January_2025.jpg'],
    date: '2026-11-05',
    endDate: '2026-11-12',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et32', name: 'Single Screening', price: 60, currency: 'SAR', description: 'One film screening', available: 500 },
      { id: 'et33', name: 'Festival Pass', price: 350, currency: 'SAR', description: 'Unlimited screenings + workshops', available: 200 },
    ],
    isTrending: false,
    isSoldOut: false,
  },
  {
    id: 'ee15',
    name: 'Boxing: Fury vs Usyk III',
    nameAr: 'ملاكمة: فيوري ضد أوسيك 3',
    description: 'The trilogy fight of the century! Heavyweight boxing returns to Riyadh with the final clash between Tyson Fury and Oleksandr Usyk.',
    type: 'sports' as const,
    venue: 'Kingdom Arena, Riyadh',
    images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Riyadh_city_%282014%29.jpg/800px-Riyadh_city_%282014%29.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Masmak_Fort_%2812753717253%29.jpg/800px-Masmak_Fort_%2812753717253%29.jpg'],
    date: '2026-08-22',
    endDate: '2026-08-22',
    city: 'Riyadh',
    ticketTypes: [
      { id: 'et34', name: 'Upper Deck', price: 300, currency: 'SAR', description: 'Upper level seating', available: 8000 },
      { id: 'et35', name: 'Floor Seats', price: 1500, currency: 'SAR', description: 'Arena floor seating', available: 2000 },
      { id: 'et36', name: 'Ringside VIP', price: 5000, currency: 'SAR', description: 'Ringside + post-fight access', available: 100 },
    ],
    isTrending: true,
    isSoldOut: false,
  },
];
