export const restaurants = [
  {
    id: 'r1',
    name: 'Nusr-Et Steakhouse',
    nameAr: 'نصرت ستيك هاوس',
    cuisine: 'Steakhouse',
    priceRange: 4 as const,
    rating: 4.6,
    reviewCount: 2840,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7116,
    longitude: 46.6742,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '30 min',
    menuHighlights: [
      { name: 'Golden Tomahawk', price: 1200, description: 'Gold-wrapped tomahawk steak', image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Ottoman Steak', price: 450, description: 'Signature Ottoman-style ribeye', image: 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Baklava Cheesecake', price: 95, description: 'Turkish-inspired dessert', image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r2',
    name: 'Zuma',
    nameAr: 'زوما',
    cuisine: 'Japanese',
    priceRange: 4 as const,
    rating: 4.7,
    reviewCount: 1950,
    images: ['https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7256,
    longitude: 46.6890,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Seafood'],
    isOpen: true,
    waitTime: '25 min',
    menuHighlights: [
      { name: 'Wagyu Tataki', price: 280, description: 'A5 wagyu beef with truffle ponzu', image: 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Black Cod Miso', price: 320, description: 'Signature marinated black cod', image: 'https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Dragon Roll', price: 145, description: 'Tempura prawn with avocado', image: 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r3',
    name: 'La Petite Maison',
    nameAr: 'لا بيتيت ميزون',
    cuisine: 'French',
    priceRange: 4 as const,
    rating: 4.5,
    reviewCount: 1650,
    images: ['https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7300,
    longitude: 46.6750,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '20 min',
    menuHighlights: [
      { name: 'Truffle Pizza', price: 185, description: 'Black truffle flatbread with burrata', image: 'https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Sea Bass Fillet', price: 245, description: 'Pan-seared with lemon caper sauce', image: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r4',
    name: 'Hakkasan',
    nameAr: 'هاكاسان',
    cuisine: 'Chinese',
    priceRange: 4 as const,
    rating: 4.6,
    reviewCount: 1420,
    images: ['https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7350,
    longitude: 46.6680,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '35 min',
    menuHighlights: [
      { name: 'Peking Duck', price: 390, description: 'Whole roasted duck with pancakes', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Dim Sum Platter', price: 175, description: 'Chef\'s selection of 8 dim sum', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r5',
    name: 'Cipriani',
    nameAr: 'شيبرياني',
    cuisine: 'Italian',
    priceRange: 4 as const,
    rating: 4.5,
    reviewCount: 980,
    images: ['https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7280,
    longitude: 46.6850,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '20 min',
    menuHighlights: [
      { name: 'Baked Tagliolini', price: 165, description: 'Signature green pasta with ham', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Beef Carpaccio', price: 135, description: 'Thinly sliced with arugula and parmesan', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r6',
    name: 'Najd Village',
    nameAr: 'قرية نجد',
    cuisine: 'Traditional Saudi',
    priceRange: 2 as const,
    rating: 4.4,
    reviewCount: 3200,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.6880,
    longitude: 46.7120,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '15 min',
    menuHighlights: [
      { name: 'Kabsa', price: 75, description: 'Traditional Saudi rice with lamb', image: 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Jareesh', price: 55, description: 'Crushed wheat porridge with meat', image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Margoog', price: 65, description: 'Thin dough with vegetables and lamb', image: 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r7',
    name: 'Al Romansiah',
    nameAr: 'الرومانسية',
    cuisine: 'Traditional Saudi',
    priceRange: 2 as const,
    rating: 4.3,
    reviewCount: 8500,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7500,
    longitude: 46.7000,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '10 min',
    menuHighlights: [
      { name: 'Mandi Lamb', price: 89, description: 'Slow-cooked lamb on fragrant rice', image: 'https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Mixed Grill', price: 95, description: 'Selection of grilled meats with sides', image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r8',
    name: 'Al Baik',
    nameAr: 'البيك',
    cuisine: 'Fast Food',
    priceRange: 1 as const,
    rating: 4.7,
    reviewCount: 25000,
    images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 21.5169,
    longitude: 39.2192,
    city: 'Jeddah',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '20 min',
    menuHighlights: [
      { name: 'Broasted Chicken Meal', price: 17, description: 'Iconic crispy chicken with garlic sauce', image: 'https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Shrimp Meal', price: 22, description: 'Crispy breaded shrimp combo', image: 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Fish Fillet', price: 19, description: 'Golden fried fish with tartar sauce', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r9',
    name: 'Mama Noura',
    nameAr: 'ماما نورة',
    cuisine: 'Traditional Saudi',
    priceRange: 1 as const,
    rating: 4.2,
    reviewCount: 12000,
    images: ['https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.6750,
    longitude: 46.6900,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '10 min',
    menuHighlights: [
      { name: 'Shawarma Plate', price: 25, description: 'Grilled shawarma with garlic and pickles', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Falafel Wrap', price: 12, description: 'Fresh falafel with tahini sauce', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r10',
    name: 'Al Tazaj',
    nameAr: 'التازج',
    cuisine: 'Grilled Chicken',
    priceRange: 1 as const,
    rating: 4.1,
    reviewCount: 9800,
    images: ['https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7100,
    longitude: 46.6750,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '15 min',
    menuHighlights: [
      { name: 'Whole Grilled Chicken', price: 45, description: 'Charcoal-grilled with signature spices', image: 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Chicken Tikka', price: 35, description: 'Marinated chicken tikka platter', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r11',
    name: '% Arabica',
    nameAr: '٪ أرابيكا',
    cuisine: 'Cafe',
    priceRange: 2 as const,
    rating: 4.5,
    reviewCount: 3100,
    images: ['https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7650,
    longitude: 46.6500,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian', 'Vegan'],
    isOpen: true,
    waitTime: '5 min',
    menuHighlights: [
      { name: 'Spanish Latte', price: 28, description: 'Signature sweetened espresso latte', image: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Matcha Latte', price: 32, description: 'Premium matcha with steamed milk', image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r12',
    name: 'Elixir Bunn',
    nameAr: 'إلكسير بن',
    cuisine: 'Cafe',
    priceRange: 2 as const,
    rating: 4.6,
    reviewCount: 4200,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7400,
    longitude: 46.6600,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '10 min',
    menuHighlights: [
      { name: 'V60 Pour Over', price: 35, description: 'Single origin pour over coffee', image: 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Pistachio Croissant', price: 22, description: 'Buttery croissant with pistachio cream', image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r13',
    name: "Barn's Coffee",
    nameAr: 'بارنز كوفي',
    cuisine: 'Cafe',
    priceRange: 2 as const,
    rating: 4.4,
    reviewCount: 5600,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7200,
    longitude: 46.6350,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '5 min',
    menuHighlights: [
      { name: 'Saffron Latte', price: 30, description: 'Arabian saffron-infused latte', image: 'https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Date Cake', price: 25, description: 'Moist cake with Medjool dates', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r14',
    name: 'LPM Restaurant',
    nameAr: 'إل بي إم',
    cuisine: 'French-Mediterranean',
    priceRange: 4 as const,
    rating: 4.5,
    reviewCount: 870,
    images: ['https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 21.5400,
    longitude: 39.1750,
    city: 'Jeddah',
    dietaryOptions: ['Halal', 'Seafood', 'Vegetarian'],
    isOpen: true,
    waitTime: '25 min',
    menuHighlights: [
      { name: 'Grilled Octopus', price: 165, description: 'Mediterranean octopus with herbs', image: 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Lamb Cutlets', price: 210, description: 'Herb-crusted lamb with ratatouille', image: 'https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r15',
    name: 'Al Mashawi Al Halabiya',
    nameAr: 'المشاوي الحلبية',
    cuisine: 'Syrian-Lebanese',
    priceRange: 2 as const,
    rating: 4.3,
    reviewCount: 6200,
    images: ['https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/2089717/pexels-photo-2089717.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.6950,
    longitude: 46.7050,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian'],
    isOpen: true,
    waitTime: '15 min',
    menuHighlights: [
      { name: 'Mixed Kebab Platter', price: 85, description: 'Assorted grilled kebabs with rice', image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Kunafa', price: 35, description: 'Crispy cheese pastry with sugar syrup', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r16',
    name: 'Urth Caffe',
    nameAr: 'أورث كافيه',
    cuisine: 'Cafe',
    priceRange: 3 as const,
    rating: 4.4,
    reviewCount: 2800,
    images: ['https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7550,
    longitude: 46.6450,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Vegetarian', 'Vegan', 'Gluten-free'],
    isOpen: true,
    waitTime: '15 min',
    menuHighlights: [
      { name: 'Avocado Toast', price: 55, description: 'Sourdough with smashed avocado and eggs', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Acai Bowl', price: 48, description: 'Organic acai with granola and berries', image: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
  {
    id: 'r17',
    name: 'Camel Step',
    nameAr: 'خطوة جمل',
    cuisine: 'Saudi Cafe',
    priceRange: 2 as const,
    rating: 4.5,
    reviewCount: 1800,
    images: ['https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.6300,
    longitude: 46.7200,
    city: 'Riyadh',
    dietaryOptions: ['Halal'],
    isOpen: true,
    waitTime: '10 min',
    menuHighlights: [
      { name: 'Saudi Coffee', price: 18, description: 'Traditional cardamom-spiced Arabic coffee', image: 'https://images.pexels.com/photos/2641886/pexels-photo-2641886.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Camel Milk Latte', price: 28, description: 'Unique latte made with camel milk', image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: true,
  },
  {
    id: 'r18',
    name: 'Sushi Samba',
    nameAr: 'سوشي سامبا',
    cuisine: 'Japanese-Brazilian Fusion',
    priceRange: 4 as const,
    rating: 4.4,
    reviewCount: 1100,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800'],
    latitude: 24.7320,
    longitude: 46.6700,
    city: 'Riyadh',
    dietaryOptions: ['Halal', 'Seafood', 'Vegetarian'],
    isOpen: true,
    waitTime: '30 min',
    menuHighlights: [
      { name: 'Yellowtail Sashimi', price: 195, description: 'Fresh yellowtail with jalapeño', image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800' },
      { name: 'Wagyu Gyoza', price: 145, description: 'Pan-fried wagyu beef dumplings', image: 'https://images.pexels.com/photos/5175529/pexels-photo-5175529.jpeg?auto=compress&cs=tinysrgb&w=800' },
    ],
    isFeatured: false,
  },
];
