export const malls = [
  {
    id: 'm1', name: 'Kingdom Centre Mall', nameAr: 'مركز المملكة', description: 'Iconic luxury shopping destination housed in the famous Kingdom Tower. Features high-end international brands, the Sky Bridge observation deck, and premium dining.', type: 'luxury' as const,
    images: ['https://picsum.photos/800/600?random=300', 'https://picsum.photos/800/600?random=301'],
    city: 'Riyadh', latitude: 24.7112, longitude: 46.6745, storeCount: 161,
    openingHours: '10:00 AM - 10:00 PM', features: ['Luxury Brands', 'Sky Bridge', 'Prayer Room', 'Valet Parking', 'Fine Dining', 'Currency Exchange'],
    promotions: [{ title: 'Summer Sale', discount: '30-70% off select brands', validUntil: '2026-08-31' }],
  },
  {
    id: 'm2', name: 'Riyadh Park', nameAr: 'الرياض بارك', description: 'One of the largest malls in Saudi Arabia with over 400 stores, a massive entertainment zone, indoor theme park, and diverse dining options.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=302', 'https://picsum.photos/800/600?random=303'],
    city: 'Riyadh', latitude: 24.6320, longitude: 46.7150, storeCount: 420,
    openingHours: '10:00 AM - 11:00 PM', features: ['400+ Stores', 'Cinema', 'Indoor Theme Park', 'Food Court', 'Prayer Room', 'Free Parking', 'Kids Play Area'],
    promotions: [{ title: 'Back to School', discount: '20% off kids brands', validUntil: '2026-09-15' }],
  },
  {
    id: 'm3', name: 'Panorama Mall', nameAr: 'بانوراما مول', description: 'Premium shopping destination in Riyadh featuring international fashion, electronics, and a stunning glass-roofed atrium with natural lighting.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=304', 'https://picsum.photos/800/600?random=305'],
    city: 'Riyadh', latitude: 24.7680, longitude: 46.6520, storeCount: 280,
    openingHours: '9:30 AM - 11:00 PM', features: ['International Brands', 'Hypermarket', 'Cinema', 'Food Court', 'Prayer Room', 'Parking'],
    promotions: [{ title: 'Weekend Specials', discount: '15% off electronics', validUntil: '2026-06-30' }],
  },
  {
    id: 'm4', name: 'Al Nakheel Mall', nameAr: 'النخيل مول', description: 'Elegant shopping complex in northern Riyadh featuring a mix of luxury and popular brands, gourmet restaurants, and a beautiful palm-tree-lined design.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=306', 'https://picsum.photos/800/600?random=307'],
    city: 'Riyadh', latitude: 24.7900, longitude: 46.6350, storeCount: 200,
    openingHours: '10:00 AM - 10:30 PM', features: ['Mixed Brands', 'Restaurants', 'Supermarket', 'Prayer Room', 'Parking', 'ATMs'],
    promotions: [],
  },
  {
    id: 'm5', name: 'Red Sea Mall', nameAr: 'ردسي مول', description: 'Jeddah\'s premier shopping destination with over 480 stores, an indoor canal with boat rides, and one of the largest food courts in the Middle East.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=308', 'https://picsum.photos/800/600?random=309'],
    city: 'Jeddah', latitude: 21.6014, longitude: 39.1265, storeCount: 484,
    openingHours: '10:00 AM - 12:00 AM', features: ['480+ Stores', 'Indoor Canal', 'Boat Rides', 'Cinema', 'Food Court', 'Prayer Room', 'Parking'],
    promotions: [{ title: 'Jeddah Season Special', discount: 'Up to 50% off fashion', validUntil: '2026-07-31' }],
  },
  {
    id: 'm6', name: 'Mall of Arabia', nameAr: 'مول العرب', description: 'A vast shopping and entertainment complex in Jeddah featuring hundreds of international brands, a snow park, and year-round family entertainment.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=310', 'https://picsum.photos/800/600?random=311'],
    city: 'Jeddah', latitude: 21.5950, longitude: 39.1450, storeCount: 350,
    openingHours: '10:00 AM - 11:00 PM', features: ['Snow Park', 'Cinema', '350+ Stores', 'Food Court', 'Kids Entertainment', 'Prayer Room'],
    promotions: [{ title: 'Summer Cool Down', discount: 'Snow Park 30% off', validUntil: '2026-08-15' }],
  },
  {
    id: 'm7', name: 'The Avenues - Riyadh', nameAr: 'الأفنيوز - الرياض', description: 'Ultra-luxury shopping destination bringing Kuwait\'s iconic Avenues concept to Riyadh with the finest international designer brands and exclusive boutiques.', type: 'luxury' as const,
    images: ['https://picsum.photos/800/600?random=312', 'https://picsum.photos/800/600?random=313'],
    city: 'Riyadh', latitude: 24.7350, longitude: 46.6580, storeCount: 150,
    openingHours: '10:00 AM - 11:00 PM', features: ['Designer Brands', 'Fine Dining', 'Art Gallery', 'VIP Shopping', 'Valet Parking', 'Concierge'],
    promotions: [],
  },
  {
    id: 'm8', name: 'Bujairi Terrace', nameAr: 'بوجيري تراس', description: 'A stunning dining and retail destination in the historic Diriyah district, featuring heritage architecture, award-winning restaurants, and artisan boutiques.', type: 'luxury' as const,
    images: ['https://picsum.photos/800/600?random=314', 'https://picsum.photos/800/600?random=315'],
    city: 'Riyadh', latitude: 24.7340, longitude: 46.5720, storeCount: 45,
    openingHours: '10:00 AM - 12:00 AM', features: ['Heritage Architecture', 'Fine Dining', 'Artisan Shops', 'Gallery Spaces', 'Diriyah Views', 'Events'],
    promotions: [{ title: 'Heritage Experience', discount: 'Free guided heritage walk', validUntil: '2026-12-31' }],
  },
  {
    id: 'm9', name: 'Via Riyadh', nameAr: 'فيا الرياض', description: 'An exclusive lifestyle destination combining luxury shopping, world-class dining, and entertainment in a stunning European-inspired open-air setting.', type: 'luxury' as const,
    images: ['https://picsum.photos/800/600?random=316', 'https://picsum.photos/800/600?random=317'],
    city: 'Riyadh', latitude: 24.7200, longitude: 46.6700, storeCount: 80,
    openingHours: '10:00 AM - 12:00 AM', features: ['Open-air Design', 'Luxury Fashion', 'Celebrity Restaurants', 'Water Features', 'Valet Parking'],
    promotions: [],
  },
  {
    id: 'm10', name: 'Souq Al Zal', nameAr: 'سوق الزل', description: 'One of the oldest traditional markets in Riyadh dating back over 100 years. Famous for antiques, Arabian perfumes, traditional clothing, and handicrafts.', type: 'traditional_souq' as const,
    images: ['https://picsum.photos/800/600?random=318', 'https://picsum.photos/800/600?random=319'],
    city: 'Riyadh', latitude: 24.6310, longitude: 46.7130, storeCount: 150,
    openingHours: '8:00 AM - 12:00 PM, 4:00 PM - 9:00 PM', features: ['Antiques', 'Arabian Perfumes', 'Traditional Clothing', 'Handicrafts', 'Gold', 'Spices', 'Bargaining'],
    promotions: [],
  },
  {
    id: 'm11', name: 'Souq Al Alawi', nameAr: 'سوق العلوي', description: 'A vibrant historic marketplace in the heart of old Jeddah (Al-Balad). Explore narrow alleys filled with spices, textiles, jewelry, and traditional Arabian goods.', type: 'traditional_souq' as const,
    images: ['https://picsum.photos/800/600?random=320', 'https://picsum.photos/800/600?random=321'],
    city: 'Jeddah', latitude: 21.4869, longitude: 39.1872, storeCount: 200,
    openingHours: '9:00 AM - 1:00 PM, 4:30 PM - 11:00 PM', features: ['Spices', 'Textiles', 'Jewelry', 'Perfumes', 'Traditional Goods', 'Street Food', 'Heritage Area'],
    promotions: [],
  },
  {
    id: 'm12', name: 'Hayat Mall', nameAr: 'حياة مول', description: 'A popular family-friendly mall in Riyadh offering a wide range of affordable fashion, electronics, entertainment, and dining options.', type: 'mega_mall' as const,
    images: ['https://picsum.photos/800/600?random=322', 'https://picsum.photos/800/600?random=323'],
    city: 'Riyadh', latitude: 24.7600, longitude: 46.7300, storeCount: 320,
    openingHours: '9:30 AM - 11:30 PM', features: ['Affordable Shopping', 'Cinema', 'Family Entertainment', 'Food Court', 'Hypermarket', 'Prayer Room'],
    promotions: [{ title: 'Family Weekend', discount: 'Buy 2 Get 1 Free on kids clothing', validUntil: '2026-05-30' }],
  },
];
